@baseURL =  http://localhost:3000
@id_calendario = 2

### Listar Calendários
GET {{baseURL}}/calendars
Accept: application/json   

### Criar Calendário
POST {{baseURL}}/calendars
Content-Type: application/json 

{
    "nome_exibicao": "Calendário de Teste - 123",
    "cor": "FF5734",
    "usuario_id": 1
}

### Atualizar Calendário existente
PUT {{baseURL}}/calendars/{{id_calendario}}
Content-Type: application/json

{
    "nome_exibicao": "Calendário de Teste Atualizado 3210",
    "cor": "00FF00",
    "criado_em": "2024-06-01 13:50:00"
}

### Atualizar Calendário inexistente (erro esperado)
PUT {{baseURL}}/calendars/9999
Content-Type: application/json

{
    "nome_exibicao": "Calendário Inexistente",
    "cor": "0000FF",
    "criado_em": "2024-06-01 12:00:00"
}

### Deletar Calendário existente
DELETE {{baseURL}}/calendars/{{id_calendario}}   
Accept: application/json

res.json() 
{
    "mensagem": "Calendário deletado com sucesso.",
}

### Deletar Calendário inexistente (erro esperado)
DELETE {{baseURL}}/calendars/9999   
Accept: application/json    

res.json() 
{
    "erro": "Calendário não encontrado."
}

